AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for Lambda functions and API Gateway

Resources:
  # Define the API Gateway
Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
      # DefinitionBody: 
      #   Fn::Transform:
      #     Name: AWS::Include
      #     Parameters:
      #       Location: ./open_api/ece461-project-phase2-fall2024-updated.yaml

  PackageRetrieve:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs18.x
      CodeUri: dist/handlers/PackageRetrieve   # Ensure this points only to the necessary code
      MemorySize: 128
      Timeout: 10
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi   # Reference the API defined above
            Path: /package/{id}
            Method: get
            RequestParameters:
              method.request.path.id: true

  PackageCreate:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs18.x
      CodeUri: dist/handlers/PackageCreate
      MemorySize: 128
      Timeout: 3
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi   # Reference the API defined above
            Path: /package
            Method: post

  PackageDelete:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs18.x
      CodeUri: dist/handlers/PackageDelete
      MemorySize: 128
      Timeout: 3
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /package/{id}
            Method: delete

  PackageUpdate:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs18.x
      CodeUri: dist/handlers/PackageUpdate
      MemorySize: 128
      Timeout: 3
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /package/{id}
            Method: put

  GetTracks:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs18.x
      CodeUri: dist/handlers/GetTracks
      MemorySize: 128
      Timeout: 3
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /tracks
            Method: get

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/"

Parameters:
  Stage:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Stage name