name: Deploy Backend to Production Environment

on:
  push:
    branches:
      - main

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Setup Sam CLI
          uses: aws-actions/setup-sam@v2

        - name: Build
          working-directory: backend
          run: tsc && sam build --use-container

        - name: Configure AWS Credentials for Production Account
          uses: aws-actions/configure-aws-credentials@v1.7.0
          with:
            role-to-assume: arn:aws:iam::864899856155:oidc-provider/token.actions.githubusercontent.com
            aws-region: us-east-2

        - name: Deploy to Production
          working-directory: backend
          run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --parameter-overrides Stage=prod