name: Deploy Backend to Dev Environment

on:
  push:
    branches:
      - dev
      - main

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Setup Sam CLI
          uses: aws-actions/setup-sam@v2

        - name: Install dependencies
          working-directory: backend
          run: npm install

        - name: Build
          working-directory: backend
          run: npm run build && sam build --use-container
          
        - name: Configure AWS Credentials - Development
          if: github.ref == 'refs/heads/dev'
          uses: aws-actions/configure-aws-credentials@v1.7.0
          with:
            role-to-assume: arn:aws:iam::122610496633:role/GitHubDeployRole
            aws-region: us-east-2

        - name: Configure AWS Credentials - Production
          if: github.ref == 'refs/heads/main'
          uses: aws-actions/configure-aws-credentials@v1.7.0
          with:
            role-to-assume: arn:aws:iam::864899856155:oidc-provider/token.actions.githubusercontent.com
            aws-region: us-east-2

        - name: Deploy to Development
          working-directory: backend
          if: github.ref == 'refs/heads/dev'
          run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --parameter-overrides Stage=dev

        - name: Deploy to Production
          working-directory: backend
          if: github.ref == 'refs/heads/main'
          run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --parameter-overrides Stage=prod