name: Enforce Dev to Main PRs

on:
  pull_request:
    branches:
      - main

jobs:
  restrict-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Base Branch
        run: |
          if [ "${{ github.event.pull_request.head.ref }}" != "dev" ]; then
            echo "Pull requests to main are only allowed from dev branch."
            exit 1
          fi
      - name: Run End-to-End Tests
        run: |
          echo "Running end-to-end tests..."
          cd backend
          npm run test:e2e
