name: Build and Test Frontend and Backend

on:
  pull_request:
    branches:
      - main
      - dev

permissions:
  contents: read
  actions: read

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Lint Frontend
        working-directory: frontend
        run: npm run lint

      - name: Lint Backend
        working-directory: backend
        run: npm run lint